function arabicSavedWords(count: number): string {
  if (count === 0) return "لا كلمات محفوظة";
  if (count === 1) return "كلمة واحدة محفوظة";
  if (count === 2) return "كلمتان محفوظتان";
  return `${count} ${count <= 10 ? "كلمات" : "كلمة"} محفوظة`;
}

function arabicLearningSummary(_readings: number, words: number): string {
  const wordSummary = words === 0
    ? "لم تحفظ أي كلمة"
    : words === 1
      ? "حفظت كلمة واحدة"
      : words === 2
        ? "حفظت كلمتين"
        : `حفظت ${words} ${words <= 10 ? "كلمات" : "كلمة"}`;

  return `${wordSummary}.`;
}

export const uiCopy = {
  ar: {
    homeLabel: "وضّح - الصفحة الرئيسية",
    languageLabel: "لغة الموقع",
    vocabularyButton: "مفرداتي",
    hero: {
      eyebrow: "افهم ← تعلّم ← تقدّم",
      title: "نقرّب المعنى،",
      accent: " ونبني الفهم.",
      description: "يقدّم لك «وضّح» النص بصياغة تناسب مستواك، ويحافظ على معناه وتفاصيله، ثم يساعدك على تعلّم مفرداته وتراكيبه حتى تقرأه بثقة.",
      secondary: "ابدأ بما تفهمه اليوم، واقرأ بثقة أكبر غداً.",
      cta: "وضّح لي",
    },
    featureShowcase: {
      eyebrow: "تعلّم من كل نص",
      title: "كل نص تفهمه، يصبح جزءاً من لغتك.",
      hint: "اختر نصاً يهمّك، واقرأه بالمستوى المناسب، ثم تعلّم الكلمات والتراكيب التي تقرّبك من صياغته كما وردت.",
      items: [
        { label: "أضف نصّك", description: "استخدم مقالاً أو خبراً أو أي محتوى عربي تريد فهمه" },
        { label: "ارفع ملف PDF", description: "اقرأ المستند كاملاً بصياغة أوضح تناسب مستواك" },
        { label: "احتفظ بمفرداتك", description: "اجمع الكلمات الجديدة وارجع إليها متى شئت" },
        { label: "افهم الشعر", description: "قرّب معنى الأبيات واحفظ كلماتها" },
      ],
    },
    audiences: {
      child: { label: "طفل", description: "جمل قصيرة وكلمات سهلة" },
      non_arabic_speaker: { label: "غير ناطق بالعربية", description: "عربية واضحة مع ترجمة إنجليزية" },
      general_reader: { label: "قارئ عام", description: "عربية واضحة ومباشرة" },
    },
    readerStep: { title: "لمن نوضّح النص؟", subtitle: "اختر القارئ لنضبط مستوى الصياغة" },
    sourceStep: { title: "ما الذي تريد فهمه؟", subtitle: "الصق نصاً عربياً أو ارفع ملف PDF" },
    source: {
      textTab: "نص عربي",
      pdfTab: "ملف PDF",
      inputLabel: "النص العربي",
      placeholder: "الصق هنا نصاً عربياً تريد فهمه…",
      choosePdf: "اختر ملف PDF بالعربية",
      pdfReady: (size: string) => `${size} MB · جاهز للقراءة`,
      pdfPrivacy: "حتى 4 MB · لا يُحفظ الملف على الخادم",
    },
    errors: {
      textTooShort: "أدخل نصاً عربياً لا يقل عن 20 حرفاً.",
      pdfRequired: "اختر ملف PDF عربي أولاً.",
      pdfTooLarge: "يجب ألا يتجاوز حجم الملف أربعة ميغابايت.",
      request: "تعذر إكمال الطلب. حاول مرة أخرى.",
      word: "تعذر شرح الكلمة.",
    },
    actions: {
      loading: "نوضّح النص ونراجع معناه…",
      loadingTitle: "نجهّز النص لك",
      loadingDetail: "نقيس صعوبة النص، ونضبط صياغته، ونراجع التفاصيل، ثم نرتّب لك مسار التدرّج. قد يستغرق ذلك لحظات.",
      wait: "يرجى الانتظار",
      start: "ابدأ",
      understandPdf: "وضّح المستند",
      clarifyText: "وضّح النص",
      sample: "جرّب مثالاً",
    },
    poetry: {
      kicker: "وضّح للشعر",
      title: "اقترب من القصيدة، من غير أن تفقد سحرها.",
      description: "ضع الأبيات كما هي؛ نقرّب معناها بيتاً بيتاً، ونترجمها إلى الإنجليزية، ونختار لك كلمات تستحق أن تعود إليها.",
      inputLabel: "النص الشعري",
      placeholder: "اكتب أو الصق هنا الأبيات التي تريد فهمها…",
      hint: "يمكنك إضافة بيت واحد أو قصيدة قصيرة.",
      submit: "قرّب المعنى",
      loading: "نقرأ الأبيات ونقرّب معناها…",
      sample: "جرّب بيتين",
      error: "أدخل بيتاً شعرياً عربياً واحداً على الأقل.",
      resultReady: "القصيدة أوضح الآن",
      overview: "المعنى العام",
      fullTranslation: "الترجمة الإنجليزية كاملة",
      linesTitle: "بيتاً بيتاً",
      linesDescription: "البيت كما ورد، ثم معناه القريب وترجمته.",
      clearMeaning: "المعنى القريب",
      translation: "الترجمة الإنجليزية",
      vocabularyTitle: "كلمات من القصيدة",
      vocabularyDescription: "احفظ ما يفيدك منها لتراجعه لاحقاً مع معناه.",
      saveWord: "احفظ الكلمة",
      savedWord: "محفوظة ✓",
      verseLabel: "وردت في",
    },
    result: {
      ready: "النص جاهز",
      title: "القراءة أوضح الآن",
      tabsLabel: "عرض النتيجة",
      views: { clear: "النص الواضح", english: "الترجمة الإنجليزية", original: "النص كما ورد" },
      wordHint: "اضغط على أي كلمة لمعرفة معناها في هذا السياق.",
      wordButtonHint: "اضغط لشرح الكلمة",
      diacritics: "تشكيل الكلمات الصعبة",
    },
    wordLens: {
      loading: (word: string) => `جارٍ فهم كلمة «${word}»…`,
      close: "إغلاق",
      root: "الجذر",
      synonym: "مرادف",
      otherMeaning: "المعنى بالإنجليزية",
      save: "احفظ في مفرداتي",
      saved: "محفوظة في مفرداتي ✓",
    },
    tools: {
      intro: "ماذا تريد أن تفعل الآن؟",
      speech: "استمع للنص",
      stopSpeech: "إيقاف القراءة",
      speechDescription: "استمع إلى النص المعروض",
      learning: "مفرداتي",
      savedCount: arabicSavedWords,
      changes: "ما الذي تغيّر؟",
      changesDescription: "قارن بين الصياغتين",
      cultural: "ما وراء العبارة",
      culturalDescription: "افهم المثل والصورة في سياقهما",
      check: "اختبر فهمك",
      checkDescription: "سؤال قصير من النص",
      visual: "المحتوى في خطوات",
      visualDescription: "رتّب الأفكار بسرعة",
      trust: "سلامة المعنى",
      trustDescription: "نتأكد من بقاء التفاصيل المهمة",
    },
    panels: {
      learningTitle: "تعلّم من هذا النص",
      learningSummary: arabicLearningSummary,
      saveWord: "+ احفظ الكلمة",
      vocabulary: "مفرداتي",
      vocabularyDescription: "تتذكر ما تتعلّمه وتستخدمه لتخصيص قراءاتك القادمة على هذا الجهاز.",
      emptyVocabulary: "لا توجد كلمات محفوظة بعد.",
      emptyVocabularyHint: "وضّح نصاً، ثم اضغط على أي كلمة واحفظها من عدسة الكلمات.",
      removeWord: (word: string) => `حذف ${word}`,
      changeTitle: "خريطة التغيير",
      changeDescription: "قارن بين الصياغتين واعرف كيف أصبح النص أوضح مع بقاء المعنى.",
      before: "قبل",
      after: "بعد",
      noChanges: "كان النص واضحاً ولم يحتج إلى تغييرات بارزة.",
      culturalTitle: "ما وراء العبارة",
      culturalDescription: "نقرّب المعنى المقصود، لا الكلمات وحدها.",
      culturalLiteral: "الصورة الحرفية",
      culturalIntended: "المقصود هنا",
      culturalContext: "ما الذي يساعد على فهمها؟",
      culturalEnglish: "المعنى بالإنجليزية",
      culturalEquivalent: "تعبير قريب بالإنجليزية",
      culturalNoEquivalent: "لا يوجد تعبير إنجليزي مطابق؛ لذلك نترجم المعنى مباشرة.",
      checkTitle: "هل وصلت الفكرة؟",
      showAnswer: "أظهر الإجابة",
      hideAnswer: "إخفاء الإجابة",
      understood: "فهمتها ✓",
      review: "أحتاج مراجعة",
      checkRecorded: "شكراً، يمكنك متابعة القراءة.",
      visualTitle: "الأفكار بالترتيب",
      visualDescription: "عرض سريع يبيّن لك تسلسل الأفكار.",
      trustTitle: "المعنى أولاً",
      trustDescription: "مراجعة ثانية تتحقق من الأسماء والأرقام والشروط والمواعيد المهمة.",
      noDetails: "لم يتضمن المحتوى تفاصيل حساسة تحتاج إلى عرض منفصل.",
    },
    footer: {
      reminder: "راجع دائماً الأسماء والأرقام والمواعيد المهمة.",
      copied: "تم النسخ ✓",
      copy: "نسخ النص",
      newContent: "محتوى جديد",
    },
    principles: {
      kicker: "عن وضّح",
      title: "نفكّ تعقيد النص، لا معناه.",
      cards: [
        { title: "أوضح، لا أقل", body: "نرتّب الفكرة ونخفف تعقيد العبارة، مع إبقاء الأسماء والتواريخ والأرقام والشروط كما هي." },
        { title: "العربية ومعناها معاً", body: "يقرأ المستخدم النص بعربية واضحة، ويجد ترجمته الإنجليزية إلى جانبه عندما يحتاج إليها." },
        { title: "خطوة أقرب كل مرة", body: "نتعلّم من النص نفسه: مفردات مختارة، سؤال قصير، ثم عودة أسهل إلى الصياغة الأصلية." },
      ],
    },
  },
  en: {
    homeLabel: "Waddeh - Home",
    languageLabel: "Website language",
    vocabularyButton: "My vocabulary",
    hero: {
      eyebrow: "Understand → Learn → Progress",
      title: "We bring meaning closer,",
      accent: " and build understanding.",
      description: "Waddeh presents the text in wording suited to your level, preserves its meaning and details, then helps you learn its vocabulary and structures so you can read with confidence.",
      secondary: "Start with what you understand today, and read with greater confidence tomorrow.",
      cta: "Try Waddeh",
    },
    featureShowcase: {
      eyebrow: "Learn from every text",
      title: "Every text you understand becomes part of your language.",
      hint: "Choose a text that matters to you, read it at the right level, then learn the words and structures that bring its wording within reach.",
      items: [
        { label: "Add your text", description: "Use an article, news story, or any Arabic content you want to understand" },
        { label: "Upload a PDF", description: "Read the full document in clearer wording suited to your level" },
        { label: "Save your vocabulary", description: "Collect new words and return to them whenever you like" },
        { label: "Understand poetry", description: "Bring the meaning of each verse closer and save its words" },
      ],
    },
    audiences: {
      child: { label: "Child", description: "Short sentences and simple words" },
      non_arabic_speaker: { label: "Non-Arabic speaker", description: "Clear Arabic with English translation" },
      general_reader: { label: "General reader", description: "Clear, direct Modern Standard Arabic" },
    },
    readerStep: { title: "Who is this text for?", subtitle: "Choose the reader so we can adjust the wording" },
    sourceStep: { title: "What would you like to understand?", subtitle: "Paste Arabic text or upload a PDF" },
    source: {
      textTab: "Arabic text",
      pdfTab: "PDF file",
      inputLabel: "Arabic text",
      placeholder: "Paste the Arabic text you want to understand…",
      choosePdf: "Choose an Arabic PDF",
      pdfReady: (size: string) => `${size} MB · Ready to read`,
      pdfPrivacy: "Up to 4 MB · The file is not stored on the server",
    },
    errors: {
      textTooShort: "Please enter at least 20 characters of Arabic text.",
      pdfRequired: "Please choose an Arabic PDF first.",
      pdfTooLarge: "The PDF must be 4 MB or smaller.",
      request: "We couldn't complete the request. Please try again.",
      word: "We couldn't explain this word. Please try again.",
    },
    actions: {
      loading: "Clarifying the text and checking its meaning…",
      loadingTitle: "Preparing your text",
      loadingDetail: "Waddeh is assessing the text, adjusting its wording, reviewing important details, and preparing your progressive reading path. This may take a moment.",
      wait: "Please wait",
      start: "Start",
      understandPdf: "Clarify document",
      clarifyText: "Clarify text",
      sample: "Try an example",
    },
    poetry: {
      kicker: "Poetry with Waddeh",
      title: "Come closer to the poem without losing its magic.",
      description: "Paste the verses as written. Waddeh explains them line by line, translates them into English, and selects useful words for later study.",
      inputLabel: "Arabic poem",
      placeholder: "Type or paste the Arabic verses you want to understand…",
      hint: "Add one verse or a short poem.",
      submit: "Bring the meaning closer",
      loading: "Reading the verses and preparing their meaning…",
      sample: "Try two verses",
      error: "Please enter at least one Arabic verse.",
      resultReady: "The poem is clearer now",
      overview: "The central meaning",
      fullTranslation: "Complete English translation",
      linesTitle: "Line by line",
      linesDescription: "The Arabic verse, its meaning in clear Arabic, and its English translation.",
      clearMeaning: "Meaning in clear Arabic",
      translation: "English translation",
      vocabularyTitle: "Words from the poem",
      vocabularyDescription: "Save useful words and review them later with their meanings.",
      saveWord: "Save word",
      savedWord: "Saved ✓",
      verseLabel: "From the verse",
    },
    result: {
      ready: "The text is ready",
      title: "Reading is clearer now",
      tabsLabel: "Result view",
      views: { clear: "Clear text", english: "English translation", original: "Text as written" },
      wordHint: "Select any Arabic word to see what it means in this context.",
      wordButtonHint: "Select to explain this word",
      diacritics: "Diacritics for difficult words",
    },
    wordLens: {
      loading: (word: string) => `Understanding “${word}”…`,
      close: "Close",
      root: "Arabic root",
      synonym: "Arabic synonym",
      otherMeaning: "Meaning in Arabic",
      save: "Save to my vocabulary",
      saved: "Saved to my vocabulary ✓",
    },
    tools: {
      intro: "What would you like to do next?",
      speech: "Listen to the text",
      stopSpeech: "Stop reading",
      speechDescription: "Listen to the text on screen",
      learning: "My Vocabulary",
      savedCount: (count: number) => `${count} saved ${count === 1 ? "word" : "words"}`,
      changes: "What changed?",
      changesDescription: "Compare the two versions",
      cultural: "Beyond the phrase",
      culturalDescription: "Understand imagery and expressions in context",
      check: "Test your understanding",
      checkDescription: "A short question from the text",
      visual: "Content in steps",
      visualDescription: "See the ideas in order",
      trust: "Meaning Integrity",
      trustDescription: "Check that important details remain",
    },
    panels: {
      learningTitle: "Learn from this text",
      learningSummary: (_readings: number, words: number) => `${words} saved ${words === 1 ? "word" : "words"}.`,
      saveWord: "+ Save word",
      vocabulary: "My Vocabulary",
      vocabularyDescription: "It remembers what you learn and uses it to personalize future readings on this device.",
      emptyVocabulary: "You have not saved any words yet.",
      emptyVocabularyHint: "Clarify a text, select any word, and save it from Word Lens.",
      removeWord: (word: string) => `Remove ${word}`,
      changeTitle: "Change Map",
      changeDescription: "Compare the two versions and see how the text became clearer while keeping its meaning.",
      before: "Before",
      after: "After",
      noChanges: "The text was already clear and did not need any major changes.",
      culturalTitle: "Beyond the phrase",
      culturalDescription: "Understand what the expression means here—not only what its words say.",
      culturalLiteral: "The literal image",
      culturalIntended: "What it means here",
      culturalContext: "Context that unlocks it",
      culturalEnglish: "Meaning in English",
      culturalEquivalent: "A close English expression",
      culturalNoEquivalent: "There is no reliable English equivalent, so Waddeh translates the intended meaning directly.",
      checkTitle: "Did the idea come through?",
      showAnswer: "Show answer",
      hideAnswer: "Hide answer",
      understood: "I understood it ✓",
      review: "I need to review",
      checkRecorded: "Thanks—continue when you are ready.",
      visualTitle: "Ideas in order",
      visualDescription: "A quick view of how the ideas unfold.",
      trustTitle: "Meaning comes first",
      trustDescription: "A second review checks important names, numbers, conditions, and dates.",
      noDetails: "The content did not include details that need a separate review.",
    },
    footer: {
      reminder: "Always review important names, numbers, and deadlines.",
      copied: "Copied ✓",
      copy: "Copy text",
      newContent: "New content",
    },
    principles: {
      kicker: "About Waddeh",
      title: "We untangle the text, not its meaning.",
      cards: [
        { title: "Clearer, not less", body: "We organize the idea and ease the wording while keeping names, dates, numbers, and conditions unchanged." },
        { title: "Arabic and its meaning, together", body: "Readers see the text in clear Arabic, with its English translation beside it whenever they need it." },
        { title: "One step closer each time", body: "We learn from the text itself: selected vocabulary, a short question, then an easier return to the original wording." },
      ],
    },
  },
} as const;

export type UiLanguage = keyof typeof uiCopy;
