export const uiCopy = {
  ar: {
    homeLabel: "وضّح - الصفحة الرئيسية",
    languageLabel: "لغة الموقع",
    vocabularyButton: "مفرداتي",
    hero: {
      eyebrow: "لأن الفهم يبدأ بالوضوح",
      title: "من النص إلى الفهم،",
      accent: " بخطوة واحدة.",
      description: "وضّح يقرّب العربية إلى كل قارئ، ويحافظ على معناها، ثم يساعده على التعلّم منها.",
      secondary: "Understand Arabic without losing what makes it Arabic.",
      cta: "ابدأ بنصك",
    },
    featureShowcase: {
      eyebrow: "ابدأ من هنا",
      title: "ماذا تريد أن تفعل؟",
      hint: "اختر طريقة واحدة، وسنرشدك في الباقي",
      items: [
        { label: "وضّح نصاً عربياً", description: "الصق النص واحصل على نسخة أوضح" },
        { label: "فهم PDF", description: "اقرأ المستند كوحدة مترابطة" },
        { label: "افتح مفرداتي", description: "راجع الكلمات التي حفظتها سابقاً" },
      ],
    },
    audiences: {
      child: { label: "طفل", description: "جمل قصيرة وكلمات سهلة" },
      non_arabic_speaker: { label: "غير ناطق بالعربية", description: "عربية واضحة مع ترجمة إنجليزية" },
      general_reader: { label: "قارئ عام", description: "عربية واضحة ومباشرة" },
    },
    readerStep: { title: "لمن تريد توضيح المحتوى؟", subtitle: "اختر القارئ" },
    sourceStep: { title: "اختر مصدر المحتوى", subtitle: "الصق نصاً عربياً أو ارفع ملف PDF" },
    source: {
      textTab: "نص عربي",
      pdfTab: "ملف PDF",
      inputLabel: "ضع النص العربي",
      placeholder: "الصق هنا نصاً عربياً تريد فهمه…",
      choosePdf: "اختر مستنداً عربياً",
      pdfReady: (size: string) => `${size} MB · جاهز للفهم`,
      pdfPrivacy: "حتى 10 MB · لا يُحفظ الملف على الخادم",
    },
    errors: {
      textTooShort: "أدخل نصاً عربياً لا يقل عن 20 حرفاً.",
      pdfRequired: "اختر ملف PDF عربي أولاً.",
      pdfTooLarge: "يجب ألا يتجاوز حجم الملف عشرة ميغابايت.",
      request: "تعذر إكمال الطلب. حاول مرة أخرى.",
      word: "تعذر شرح الكلمة.",
    },
    actions: {
      loading: "جارٍ الفهم…",
      wait: "يرجى الانتظار",
      start: "ابدأ",
      understandPdf: "افهم المستند",
      clarifyText: "وضّح النص",
      sample: "جرّب وضّح بنص جاهز",
    },
    result: {
      ready: "النتيجة جاهزة",
      title: "نصك، بصورة أوضح",
      tabsLabel: "عرض النتيجة",
      views: { clear: "العربية الواضحة", english: "English", original: "النص الأصلي" },
      wordHint: "اضغط على أي كلمة لفتح عدسة الكلمات.",
      wordButtonHint: "اضغط لشرح الكلمة",
      diacritics: "تشكيل الكلمات الصعبة",
    },
    wordLens: {
      loading: (word: string) => `جارٍ فهم كلمة «${word}»…`,
      close: "إغلاق",
      root: "الجذر",
      synonym: "مرادف",
      otherMeaning: "English",
      save: "احفظ في مفرداتي",
      saved: "محفوظة في مفرداتي ✓",
    },
    tools: {
      intro: "أدوات اختيارية — استخدم ما يساعدك فقط",
      speech: "استمع للنص",
      stopSpeech: "إيقاف القراءة",
      speechDescription: "قراءة عربية أو إنجليزية",
      learning: "التعلّم والمفردات",
      savedCount: (count: number) => `${count} كلمات محفوظة`,
      changes: "خريطة التغيير",
      changesDescription: "ماذا تغيّر، ولماذا؟",
      check: "تحقق من فهمك",
      checkDescription: "سؤال قصير من النص",
      visual: "المحتوى في خطوات",
      visualDescription: "رؤية بصرية سريعة",
      trust: "فحص المعنى",
      trustDescription: "التفاصيل التي بقيت كما هي",
    },
    panels: {
      learningTitle: "تعلّم من النص نفسه",
      learningSummary: (readings: number, words: number) => `أنجزت ${readings} قراءات، وحفظت ${words} مفردات.`,
      saveWord: "+ احفظ الكلمة",
      vocabulary: "مفرداتي",
      vocabularyDescription: "الكلمات التي حفظتها من قراءاتك.",
      emptyVocabulary: "لا توجد كلمات محفوظة بعد.",
      emptyVocabularyHint: "وضّح نصاً، ثم المس أي كلمة واحفظها من عدسة الكلمات.",
      removeWord: (word: string) => `حذف ${word}`,
      changeTitle: "خريطة التغيير",
      changeDescription: "نريك كيف أصبح التعبير أوضح من دون أن يبتعد عن أصله.",
      before: "قبل",
      after: "بعد",
      noChanges: "لم يحتج هذا المحتوى إلى تغييرات بارزة.",
      checkTitle: "هل وصلت الفكرة؟",
      showAnswer: "أظهر الإجابة",
      hideAnswer: "إخفاء الإجابة",
      understood: "فهمتها ✓",
      review: "أحتاج مراجعة",
      checkRecorded: "شكراً، يمكنك متابعة القراءة.",
      visualTitle: "المحتوى في خطوات",
      visualDescription: "مسار سريع يساعدك على رؤية ترتيب الأفكار.",
      trustTitle: "المعنى أولاً",
      trustDescription: "هذه التفاصيل الحساسة بقيت حاضرة في النص الواضح.",
      noDetails: "لم يتضمن المحتوى تفاصيل حساسة تحتاج إلى عرض منفصل.",
    },
    footer: {
      reminder: "راجع دائماً الأسماء والأرقام والمواعيد المهمة.",
      copied: "تم النسخ ✓",
      copy: "نسخ النص",
      newContent: "محتوى جديد",
    },
    principles: {
      kicker: "الفكرة التي تقود وضّح",
      title: "نفكّ تعقيد النص، لا معناه.",
      cards: [
        { title: "أوضح، لا أقل", body: "نرتّب الفكرة ونخفف تعقيد العبارة، مع إبقاء الأسماء والتواريخ والأرقام والشروط كما هي." },
        { title: "العربية ومعناها معاً", body: "يقرأ المستخدم النص بعربية واضحة، ويجد ترجمته الإنجليزية إلى جانبه عندما يحتاج إليها." },
        { title: "خطوة أقرب كل مرة", body: "نتعلّم من النص نفسه: مفردات مختارة، سؤال قصير، ثم عودة أسهل إلى الصياغة الأصلية." },
      ],
    },
  },
  en: {
    homeLabel: "Waddeh - Home",
    languageLabel: "Website language",
    vocabularyButton: "My words",
    hero: {
      eyebrow: "Because understanding starts with clarity",
      title: "From Arabic text to",
      accent: " real understanding.",
      description: "Waddeh makes Arabic clearer without losing its meaning, then helps you learn from what you read.",
      secondary: "",
      cta: "Start with your text",
    },
    featureShowcase: {
      eyebrow: "Start here",
      title: "What would you like to do?",
      hint: "Choose one option and we will guide you through the rest",
      items: [
        { label: "Clarify Arabic text", description: "Paste Arabic text and receive a clearer version" },
        { label: "PDF understanding", description: "Read a document as one connected whole" },
        { label: "Open saved vocabulary", description: "Review words you saved from earlier readings" },
      ],
    },
    audiences: {
      child: { label: "Child", description: "Short sentences and simple words" },
      non_arabic_speaker: { label: "Non-Arabic speaker", description: "Clear Arabic with English translation" },
      general_reader: { label: "General reader", description: "Clear, direct Modern Standard Arabic" },
    },
    readerStep: { title: "Who are you making this clear for?", subtitle: "Choose the reader" },
    sourceStep: { title: "Choose your content", subtitle: "Paste Arabic text or upload a PDF" },
    source: {
      textTab: "Arabic text",
      pdfTab: "PDF file",
      inputLabel: "Paste the Arabic text",
      placeholder: "Paste the Arabic text you want to understand…",
      choosePdf: "Choose an Arabic document",
      pdfReady: (size: string) => `${size} MB · Ready to understand`,
      pdfPrivacy: "Up to 10 MB · The file is not stored on the server",
    },
    errors: {
      textTooShort: "Please enter at least 20 characters of Arabic text.",
      pdfRequired: "Please choose an Arabic PDF first.",
      pdfTooLarge: "The PDF must be 10 MB or smaller.",
      request: "We couldn't complete the request. Please try again.",
      word: "We couldn't explain this word. Please try again.",
    },
    actions: {
      loading: "Understanding…",
      wait: "Please wait",
      start: "Start",
      understandPdf: "Understand the document",
      clarifyText: "Make the text clear",
      sample: "Try Waddeh with an example",
    },
    result: {
      ready: "Your result is ready",
      title: "Your text, made clear",
      tabsLabel: "Result view",
      views: { clear: "Clear Arabic", english: "English", original: "Original Arabic" },
      wordHint: "Select any Arabic word to open Word Lens.",
      wordButtonHint: "Select to explain this word",
      diacritics: "Helpful Arabic diacritics",
    },
    wordLens: {
      loading: (word: string) => `Understanding “${word}”…`,
      close: "Close",
      root: "Arabic root",
      synonym: "Arabic synonym",
      otherMeaning: "Arabic meaning",
      save: "Save to my vocabulary",
      saved: "Saved to my vocabulary ✓",
    },
    tools: {
      intro: "Optional tools — use only what helps you",
      speech: "Listen to the text",
      stopSpeech: "Stop reading",
      speechDescription: "Arabic or English read-aloud",
      learning: "Learning and vocabulary",
      savedCount: (count: number) => `${count} saved words`,
      changes: "Change Map",
      changesDescription: "What changed, and why?",
      check: "Check your understanding",
      checkDescription: "A short question from the text",
      visual: "Content in steps",
      visualDescription: "A quick visual sequence",
      trust: "Meaning check",
      trustDescription: "Important details that stayed intact",
    },
    panels: {
      learningTitle: "Learn from the text itself",
      learningSummary: (readings: number, words: number) => `${readings} readings completed and ${words} words saved.`,
      saveWord: "+ Save word",
      vocabulary: "My vocabulary",
      vocabularyDescription: "Words you have saved from your readings.",
      emptyVocabulary: "You have not saved any words yet.",
      emptyVocabularyHint: "Clarify a text, select an Arabic word, and save it from Word Lens.",
      removeWord: (word: string) => `Remove ${word}`,
      changeTitle: "Change Map",
      changeDescription: "See how each expression became clearer without moving away from its meaning.",
      before: "Before",
      after: "After",
      noChanges: "This content did not need any major wording changes.",
      checkTitle: "Did the idea come through?",
      showAnswer: "Show answer",
      hideAnswer: "Hide answer",
      understood: "I understood it ✓",
      review: "I need to review",
      checkRecorded: "Thanks—continue when you are ready.",
      visualTitle: "Content in steps",
      visualDescription: "A quick path through the order of the ideas.",
      trustTitle: "Meaning comes first",
      trustDescription: "These important details remain present in the clear version.",
      noDetails: "This content did not include critical details that need a separate list.",
    },
    footer: {
      reminder: "Always review important names, numbers, and deadlines.",
      copied: "Copied ✓",
      copy: "Copy text",
      newContent: "New content",
    },
    principles: {
      kicker: "The idea behind Waddeh",
      title: "We untangle the text, not its meaning.",
      cards: [
        { title: "Clearer, not less", body: "We simplify the expression while keeping names, dates, numbers, requirements, and conditions intact." },
        { title: "Arabic and its meaning together", body: "Read clear Arabic and open a complete English translation whenever you need it." },
        { title: "One step closer each time", body: "Learn from the text through selected vocabulary, a short check, and an easier path back to the original wording." },
      ],
    },
  },
} as const;

export type UiLanguage = keyof typeof uiCopy;
