import type { UiLanguage } from "@/lib/waddeh-store";

export const v4Copy = {
  ar: {
    shell: { home: "الرئيسية", learning: "تعلّمي", profile: "الملف", signIn: "تسجيل الدخول", start: "ابدأ الآن", language: "English" },
    home: {
      eyebrow: "العربية أقرب مما تبدو",
      title: "كل نص تفهمه،",
      accent: "يصبح جزءاً من لغتك.",
      description: "وضّح يقرّب النص إلى مستواك، ويشرح مفرداته في سياقها، ثم يساعدك على العودة إليه بفهم أعمق.",
      scrollToComposer: "ابدأ من نصك",
      solutionEyebrow: "الحل الذي يقدّمه وضّح",
      solutionTitle: "نقرّب المعنى، ونبني الفهم.",
      solutionDescription: "من النصوص والمستندات إلى الشعر والمفردات، يجمع وضّح الفهم والتعلّم في تجربة واحدة.",
      solutionItems: [
        { title: "أوضح، لا أقل", description: "نشرح النص أو ملف PDF، مع الحفاظ على الأسماء والأرقام والتفاصيل." },
        { title: "اقترب من القصيدة، من غير أن تفقد سحرها.", description: "نقرّب معنى الأبيات وصورها، مع ترجمة إنجليزية عند الحاجة." },
        { title: "تعلّم من كل نص", description: "احفظ المفردات، اختبرها في سياق جديد، وتابع خريطة التمكّن." },
      ],
      placeholder: "الصق أو اكتب العربية هنا…",
      standard: "عادي",
      poetry: "شعر",
      attach: "أرفق PDF",
      removeAttachment: "إزالة المرفق",
      submit: "ابدأ الفهم",
      sample: "جرّب مثالاً",
      preferences: "مستوى القراءة",
      continue: "تابع التعلّم",
      viewLearning: "عرض تعلّمي",
      textShort: "أدخل نصاً عربياً لا يقل عن 20 حرفاً.",
      poetryShort: "أدخل بيتاً شعرياً واحداً على الأقل.",
      pdfLarge: "يجب ألا يتجاوز حجم ملف PDF عشرة ميغابايت.",
      pdfOnly: "اختر ملف PDF صالحاً.",
      drop: "أسقط ملف PDF هنا",
    },
    reading: {
      back: "رجوع",
      processing: ["نقرأ العربية…", "نفهم السياق…", "نجهّز قراءتك…"],
      processingNote: "نبقي المعنى والتفاصيل المهمة في موضعها. قد يستغرق ذلك لحظات.",
      retry: "حاول مرة أخرى",
      newReading: "قراءة جديدة",
      understand: "افهم",
      simplify: "بسّط",
      learn: "تعلّم",
      arabic: "العربية التي تقرؤها",
      naturalMeaning: "المعنى الطبيعي",
      explanation: "السياق والدلالة",
      clearerArabic: "عربية أوضح",
      diacritics: "تشكيل الكلمات الصعبة",
      changes: "ما الذي تغيّر؟",
      before: "قبل",
      after: "بعد",
      expressions: "تعبيرات تستحق أن تعرفها",
      vocabulary: "مفردات من هذا النص",
      save: "احفظ",
      saved: "محفوظة",
      explore: "استكشف",
      exploreTitle: "استكشف هذه القراءة",
      test: "اختبر فهمك",
      threads: "خيوط المعنى",
      insights: "لمحات لغوية",
      path: "مسار التدرّج",
      details: "تفاصيل القراءة",
      close: "إغلاق",
      copy: "نسخ",
      copied: "تم النسخ",
      original: "النص الأصلي",
      readability: "قابلية القراءة",
      integrity: "سلامة المعنى",
      noLearning: "لم تُستخرج عناصر تعلّم موثوقة من هذا النص القصير.",
      viewPath: "عرض المسار في تعلّمي",
    },
    learning: {
      title: "تعلّمي",
      description: "ما تتذكره وضّح من قراءاتك، وما يستحق أن تراجعه الآن.",
      overview: "نظرة عامة",
      vocabulary: "المفردات",
      history: "القراءات",
      path: "المسار",
      map: "خريطة التعلّم",
      continue: "تابع من حيث توقفت",
      readyReview: "جاهز للمراجعة",
      recent: "قراءات حديثة",
      allReadings: "كل القراءات",
      emptyReadings: "لا توجد قراءات محفوظة بعد.",
      emptyWords: "لم تحفظ أي كلمة بعد.",
      start: "ابدأ بقراءة عربية",
      words: "كلمات",
      expressions: "تعبيرات",
      search: "ابحث بالعربية أو المعنى…",
      all: "الكل",
      learningFilter: "قيد التعلّم",
      familiar: "مألوفة",
      review: "ابدأ المراجعة",
      reveal: "أظهر الإجابة",
      knew: "عرفتها",
      again: "راجعها ثانية",
      next: "التالي",
      source: "من قراءة",
      remove: "حذف",
      level: "مستوى القراءة الحالي",
      placement: "حدّد نقطة البداية",
      manual: "اختر المستوى يدوياً",
      bridge: "أعلى مستوى تدرّج وصلت إليه",
      checks: "اختبارات الفهم",
      needsAttention: "أنماط طلبت دعماً فيها",
      noSignals: "ستظهر الأنماط هنا عندما تفتح خيوط المعنى في قراءاتك.",
    },
  },
  en: {
    shell: { home: "Home", learning: "My Learning", profile: "Profile", signIn: "Sign in", start: "Start now", language: "العربية" },
    home: {
      eyebrow: "Arabic is closer than it seems",
      title: "Every text you understand",
      accent: "becomes part of your language.",
      description: "Waddeh brings a text closer to your level, explains its vocabulary in context, then helps you return to it with deeper understanding.",
      scrollToComposer: "Start with your text",
      solutionEyebrow: "The Waddeh solution",
      solutionTitle: "We bring meaning closer and build understanding.",
      solutionDescription: "From texts and documents to poetry and vocabulary, Waddeh brings understanding and learning into one experience.",
      solutionItems: [
        { title: "Clearer, never less", description: "Understand text or a PDF while names, numbers, and important details stay in place." },
        { title: "Come closer to the poem without losing its magic.", description: "Explore each verse and its imagery, with an English translation when needed." },
        { title: "Learn from every text", description: "Save vocabulary, test it in a new context, and follow your Mastery Map." },
      ],
      placeholder: "Paste or type Arabic…",
      standard: "Standard",
      poetry: "Poetry",
      attach: "Attach PDF",
      removeAttachment: "Remove attachment",
      submit: "Start understanding",
      sample: "Try an example",
      preferences: "Reading level",
      continue: "Continue learning",
      viewLearning: "View My Learning",
      textShort: "Enter at least 20 characters of Arabic text.",
      poetryShort: "Enter at least one Arabic verse.",
      pdfLarge: "The PDF must be 10 MB or smaller.",
      pdfOnly: "Choose a valid PDF file.",
      drop: "Drop a PDF here",
    },
    reading: {
      back: "Back",
      processing: ["Reading the Arabic…", "Understanding the context…", "Preparing your reading…"],
      processingNote: "Waddeh is keeping the meaning and important details in place. This may take a moment.",
      retry: "Try again",
      newReading: "New reading",
      understand: "Understand",
      simplify: "Simplify",
      learn: "Learn",
      arabic: "The Arabic you are reading",
      naturalMeaning: "Natural meaning",
      explanation: "Context and nuance",
      clearerArabic: "Clearer Arabic",
      diacritics: "Diacritics for difficult words",
      changes: "What changed?",
      before: "Before",
      after: "After",
      expressions: "Expressions worth knowing",
      vocabulary: "Vocabulary in this text",
      save: "Save",
      saved: "Saved",
      explore: "Explore",
      exploreTitle: "Explore this reading",
      test: "Test your understanding",
      threads: "Meaning Thread",
      insights: "Language insights",
      path: "Progressive Path",
      details: "Reading details",
      close: "Close",
      copy: "Copy",
      copied: "Copied",
      original: "Original text",
      readability: "Readability",
      integrity: "Meaning integrity",
      noLearning: "No reliable learning items were extracted from this short text.",
      viewPath: "View the path in My Learning",
    },
    learning: {
      title: "My Learning",
      description: "What Waddeh remembers from your readings, and what is worth reviewing now.",
      overview: "Overview",
      vocabulary: "Vocabulary",
      history: "History",
      path: "Path",
      map: "Learning Map",
      continue: "Continue where you left off",
      readyReview: "Ready to review",
      recent: "Recent readings",
      allReadings: "All readings",
      emptyReadings: "You have no saved readings yet.",
      emptyWords: "You have not saved any words yet.",
      start: "Start an Arabic reading",
      words: "Words",
      expressions: "Expressions",
      search: "Search Arabic or meaning…",
      all: "All",
      learningFilter: "Learning",
      familiar: "Familiar",
      review: "Start review",
      reveal: "Reveal answer",
      knew: "I knew it",
      again: "Review again",
      next: "Next",
      source: "From reading",
      remove: "Remove",
      level: "Current reading level",
      placement: "Find my starting point",
      manual: "Choose level manually",
      bridge: "Highest Bridge level reached",
      checks: "Comprehension checks",
      needsAttention: "Patterns where you asked for support",
      noSignals: "Patterns will appear after you open Meaning Threads in your readings.",
    },
  },
} as const satisfies Record<UiLanguage, unknown>;

export function copyFor(language: UiLanguage) {
  return v4Copy[language];
}
